trigger:
  none

jobs:
- job: BuildCqrsSdk
  displayName: Build CQRS SDK
  pool:
    vmImage: ubuntu-latest
  variables:
    BuildConfiguration: 'Release'
    BuildPlatform: 'any cpu'
  steps:
  - task: NuGetToolInstaller@1
    displayName: Install NuGet 5.5.0
    inputs:
      versionSpec: '5.5.0'
      checkLatest: true
  - task: UseDotNet@2
    displayName: Use .NET Core 6.0.x
    inputs:
      packageType: 'sdk'
      version: '5.0.x'
  - task: NuGetCommand@2
    displayName: Restore Solution
    inputs:
      command: 'restore'
      restoreSolution: 'src/CQRS.Mediatr.Lite.sln'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    displayName: Build Library Projects
    inputs:
      command: 'build'
      projects: 'src/sdk/CQRS.Mediatr.Lite.SDK.csproj'
  - task: DotNetCoreCLI@2
    displayName: Test Projects
    inputs:
      command: 'test'
      projects: '**/*.Tests.csproj'
- job: BuildSample
  displayName: Build Sample
  pool:
    vmImage: ubuntu-latest
  variables:
    BuildConfiguration: 'Release'
    BuildPlatform: 'any cpu'
  steps:
  - task: NuGetToolInstaller@1
    displayName: Install NuGet 5.5.0
    inputs:
      versionSpec: '5.5.0'
      checkLatest: true
  - task: UseDotNet@2
    displayName: Use .NET Core 6.0.x
    inputs:
      packageType: 'sdk'
      version: '5.0.x'
  - task: NuGetCommand@2
    displayName: Restore Solution
    inputs:
      command: 'restore'
      restoreSolution: 'samples/CQRS.Mediatr.Lite.Samples/CQRS.Mediatr.Lite.Samples.sln'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    displayName: Build Library Projects
    inputs:
      command: 'build'
      projects: 'samples/CQRS.Mediatr.Lite.Samples/CQRS.Mediatr.Lite.Samples.NetCoreApi/CQRS.Mediatr.Lite.Samples.NetCoreApi.csproj'

