name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
       
    - name: Setup .NET
      uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb # v1.10.1
      with:
       dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore **/CQRS.Mediatr.Lite.sln
    
    - name: Build
      run: dotnet build **/CQRS.Mediatr.Lite.sln --no-restore
    
    - name: Test
      run: dotnet test src/tests/CQRS.Mediatr.Lite.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    
    - name: Publish to coveralls
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: src/tests/TestResults/coverage.info
