name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
       
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Manually Install libssl1.1
      run: |
        sudo apt-get update
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.1/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
        sudo apt-get install -f  # Fix any missing dependencies

    - name: Restore dependencies
      run: dotnet restore **/CQRS.Mediatr.Lite.sln
    
    - name: Build
      run: dotnet build **/CQRS.Mediatr.Lite.sln --no-restore
    
    - name: Test
      run: dotnet test src/tests/CQRS.Mediatr.Lite.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    
    - name: Publish to coveralls
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: src/tests/TestResults/coverage.info
