# This workflow will publish the AppInsights.Telemetry.AspNetCore.Extension package to https://nuget.org

name: Release
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore **/CQRS.Mediatr.Lite.sln
    - name: Build
      run: dotnet build **/CQRS.Mediatr.Lite.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test **/CQRS.Mediatr.Lite.sln --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack src/sdk/CQRS.Mediatr.Lite.SDK.csproj
    - name: Publish
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NuGet_API_Key }} --source https://api.nuget.org/v3/index.json
