# This workflow will publish the AppInsights.Telemetry.AspNetCore.Extension package to https://nuget.org

name: Release
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb # v1.10.1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore **/CQRS.Mediatr.Lite.sln
    - name: Build
      run: dotnet build **/CQRS.Mediatr.Lite.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test **/CQRS.Mediatr.Lite.sln --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack src/sdk/CQRS.Mediatr.Lite.SDK.csproj
    - name: Publish
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NuGet_API_Key }} --source https://api.nuget.org/v3/index.json
